# Generated by Django 5.2.6 on 2025-11-19 10:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Указывает, подтверждён ли email пользователя.', verbose_name='Email подтверждён'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, help_text='Необязательно', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Токен подтверждения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания токена'),
        ),
    ]
